function constants() {
  const CommercialData = [
    {
      title: "Free Listing",
      duration: "30 Days",
      price: "Free",
      features: {
        "Number Of Listings": "5",
        "Response Rate": "2X More",
        "Position On Search": "Low",
        "Buyers Visibility": "Limited",
        "Verified Tag": "No",
        "Visibility on Best Details": "No",
        "Visibility on Latest Details": "No",
        "Land Page AD": "No",
        "Land Page Banner": "No",
        "Listings Page Small ADS": "No",
        "Dedicated Agent Support": "No",
        Creatives: "No",
        "Listing Support": "No",
        "Meta ADS": "No",
        "Prime Promition": "No",
        CRM: "No",
      },
    },
    {
      title: "Basic",
      duration: "120 Days",
      price: 6999,
      features: {
        "Number Of Listings": "15",
        "Response Rate": "3X More",
        "Position On Search": "Medium",
        "Buyers Visibility": "Limited",
        "Verified Tag": "No",
        "Visibility on Best Details": "No",
        "Visibility on Latest Details": "No",
        "Land Page AD": "yes",
        "Land Page Banner": "No",
        "Listings Page Small ADS": "yes",
        "Dedicated Agent Support": "No",
        Creatives: "No",
        "Listing Support": "No",
        "Meta ADS": "No",
        "Prime Promition": "No",
        CRM: "No",
      },
    },
    {
      title: "Prime",
      duration: "180 Days",
      price: 24999,
      isPopular: true,
      features: {
        "Number Of Listings": "50",
        "Response Rate": "5X More",
        "Position On Search": "High",
        "Buyers Visibility": "Unlimited",
        "Verified Tag": "Yes",
        "Visibility on Best Details": "yes",
        "Visibility on Latest Details": "yes",
        "Land Page AD": "yes",
        "Land Page Banner": "yes",
        "Listings Page Small ADS": "yes",
        "Dedicated Agent Support": "No",
        Creatives: "No",
        "Listing Support": "No",
        "Meta ADS": "No",
        "Prime Promition": "No",
        CRM: "yes",
      },
    },
    {
      title: "Prime Plus",
      duration: "365 Days",
      price: 49999,
      features: {
        "Number Of Listings": "200",
        "Response Rate": "200",
        "Position On Search": "5X More",
        "Buyers Visibility": "Unlimited",
        "Verified Tag": "yes",
        "Visibility on Best Details": "yes",
        "Visibility on Latest Details": "yes",
        "Land Page AD": "yes",
        "Land Page Banner": "yes",
        "Listings Page Small ADS": "yes",
        "Dedicated Agent Support": "yes",
        Creatives: "yes",
        "Listing Support": "yes",
        "Meta ADS": "yes",
        "Prime Promition": "yes",
        CRM: "yes",
      },
    },
  ];
  return { CommercialData };
}

export default constants;
